vich_uploader:
  db_driver: orm
  mappings:
    product_images:
      uri_prefix: '%app.path.product_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
    slide_images:
      uri_prefix: '%app.path.slide_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.slide_images%'