<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container90yHK1R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container90yHK1R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container90yHK1R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container90yHK1R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container90yHK1R\App_KernelDevDebugContainer([
    'container.build_hash' => '90yHK1R',
    'container.build_id' => '83e9016d',
    'container.build_time' => 1595500173,
], __DIR__.\DIRECTORY_SEPARATOR.'Container90yHK1R');
